#define QUESTION1 "¿Cómo descubrieron el protocolo, la dirección y el puerto para conectarse?"
#define QUESTION2 "¿Qué diferencias hay entre TCP y UDP y en qué casos conviene usar cada uno?"
#define QUESTION3 "¿El puerto que usaron para conectarse al server es el mismo que usan para mandar las respuestas? ¿Por qué?"
#define QUESTION4 "¿Qué útil abstracción es utilizada para comunicarse con sockets? ¿se puede utilizar read(2) y write(2) para operar?"
#define QUESTION5 "¿Cómo garantiza TCP que los paquetes llegan en orden y no se pierden?"
#define QUESTION6 "Un servidor suele crear un nuevo proceso o thread para atender las conexiones entrantes. ¿Qué conviene más?"
#define QUESTION7 "¿Cómo se puede implementar un servidor que atienda muchas conexiones sin usar procesos ni threads?"
#define QUESTION8 "¿Qué aplicaciones se pueden utilizar para ver el tráfico por la red?"
#define QUESTION9 "sockets es un mecanismo de IPC. ¿Qué es más eficiente entre sockets y pipes?"
#define QUESTION10 "¿Cuáles son las características del protocolo SCTP?"
#define QUESTION11 "¿Qué es un RFC?"
#define QUESTION12 "¿Fue divertido?"

#define MESSAGE1 "Bienvenidos al TP3 y felicitaciones, ya resolvieron el primer acertijo.\n\nEn este TP deberán finalizar el juego que ya comenzaron resolviendo los desafíos de cada nivel.\nAdemás tendrán que investigar otras preguntas para responder durante la defensa.\nEl desafío final consiste en crear un programa que se comporte igual que yo, es decir, que provea los mismos desafíos y que sea necesario hacer lo mismo para resolverlos. No basta con esperar la respuesta.\nAdemás, deberán implementar otro programa para comunicarse conmigo.\n\nDeberán estar atentos a los easter eggs.\n\nPara verificar que sus respuestas tienen el formato correcto respondan a este desafío con la palabra 'entendido\\n'\n"
#define MESSAGE2 "The Wire S1E5\n5295 888 6288\n\n"
#define MESSAGE3 "https://ibb.co/tc0Hb6w\n\n"
#define MESSAGE4 "EBADF...\n\n"
#define MESSAGE5 "respuesta = strings:245\n\n"
#define MESSAGE6 ".data .bss .comment ? .shstrtab .symtab .strtab\n\n"
#define MESSAGE7 "Filter error\n"
#define MESSAGE8 "¿?\n\n\033[30;40mLa respuesta es BUmyYq5XxXGt\033[0m\n\n"
#define MESSAGE9 "Latexme\n\nSi\n\\mathrm{d}y = u^v{\\cdot}(v'{\\cdot}\\ln{(u)}+v{\\cdot}\\frac{u'}{u})\nentonces\ny =\n\n"
#define MESSAGE10 "quine.\n\n"
#define MESSAGE11 "b gdbme y encontrá el valor mágico ENTER para reintentar.\n\n"
#define MESSAGE12 "Me conoces\n\n"